comment_width = 100
condense_wildcard_suffixes = true
edition = "2021"
format_code_in_doc_comments = true
hard_tabs = true
imports_granularity = "One"
match_arm_blocks = false
match_block_trailing_comma = true
max_width = 120
newline_style = "Unix"
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
skip_children = true
tab_spaces = 2
trailing_semicolon = false
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
ignore = ["sys", "src/auto"]
