[package]
name = "wireplumber"
version = "0.1.0"
authors = ["arcnmx"]
build = "build.rs"
edition = "2018"
resolver = "2"

description = "Wireplumber GObject bindings"
keywords = ["pipewire", "wireplumber", "gobject"]

documentation = "http://docs.rs/wireplumber/"
repository = "https://github.com/arcnmx/wireplumber.rs"
readme = "README.md"
license = "MIT"

[package.metadata.docs.rs]
features = ["dox", "v0_4_3"]

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
libc = "0.2"
glib = "0.14"
gio = "0.14"
pipewire-sys = { version = "0.4" }
libspa-sys = { version = "0.4" }
pipewire = { version = "0.4", optional = true }
libspa = { version = "0.4", optional = true }
futures-util = { version = "0.3", optional = true }
ffi = { version = "0.1.0", path = "sys", package = "wireplumber-sys", features = ["v0_4_3"] }
bitflags = "1.3"
glib-signal = { version = "0.1.0", git = "https://github.com/arcnmx/glib-signal.rs.git" }

[build-dependencies]
pkg-config = "0.3"
semver = "1.0"

[features]
default = ["libspa"]
enable-futures = ["futures-util", "glib-signal/enable-futures"]
v0_4_2 = ["ffi/v0_4_2"]
v0_4_3 = ["ffi/v0_4_3", "v0_4_2"]
dox = ["ffi/dox", "glib-signal/dox"]

[workspace]
members = ["sys", "examples"]
