[options]
library = "Wp"
version = "0.4"
target_path = "."
min_cfg_version = "0.4"
work_mode = "normal"
split_build_rs = true
generate_display_trait = false
# trust_return_value_nullability = true # TODO: manually go through everything...
single_version_file = "sys/generate/src/Gir.version"

external_libraries = ["GLib", "GObject", "Gio"]
generate = [
	"Wp.Proxy",
	"Wp.ObjectInterest",
	"Wp.GlobalProxy",
	"Wp.Plugin", "Wp.ComponentLoader",
	"Wp.SessionItem", "Wp.SessionItemFeatures",
	"Wp.SiLink", "Wp.SiLinkable", "Wp.SiFactory",
	"Wp.SpaDevice", "Wp.SpaDeviceFeatures", "Wp.SpaPodBuilder",
	"Wp.SpaJson", "Wp.SpaJsonBuilder", "Wp.SpaJsonParser",
	"Wp.State",
	"Wp.Dbus", "Wp.DbusFeatures",
	"Wp.ProxyFeatures",
	"Wp.PluginFeatures",
	"Wp.NodeFeatures",
	"Wp.Object",
	"Wp.Client", "Wp.Device", "Wp.Endpoint", "Wp.Factory", "Wp.Node", "Wp.Link", "Wp.Port",
	"Wp.ObjectManager",
	"Wp.ImplEndpoint",
	"Wp.FeatureActivationTransition",
	"Wp.SiEndpoint", "Wp.ImplMetadata",
	"Wp.ImplModule", "Wp.ImplNode",
	"Wp.InitFlags", "Wp.InterestMatch", "Wp.InterestMatchFlags",
	"Wp.LookupDirs",
	"Wp.MetadataFeatures", "Wp.Metadata",
]

manual = [
	"Wp.SpaIdTable", "Wp.SpaIdValue",
	"Wp.IteratorMethods",
	"GLib.Error", "GLib.Variant", "GLib.MainContext", "GLib.Source", "GLib.SourceFunc", "GLib.DestroyNotify", "GLib.Quark", "GLib.LogLevelFlags", "GLib.LogField", "GLib.LogWriterOutput",
	"GObject.Closure", "GObject.Value", "GObject.Object",
	"Gio.Cancellable", "Gio.AsyncReadyCallback", "Gio.AsyncResult",
	"Gio.DBusConnection", "Gio.BusType"
]

[[object]]
name = "Wp.SpaType"
status = "manual"
conversion_type = "scalar"

[[object]]
name = "Wp.Core"
status = "generate"
	[[object.function]]
	name = "clone"
	ignore = true

[[object]]
name = "Wp.SiAcquisition"
status = "generate"
	[[object.function]]
	name = "acquire"
	manual = true

[[object]]
name = "Wp.SiAdapter"
status = "generate"
	[[object.function]]
	name = "set_ports_format"
	manual = true

[[object]]
name = "Wp.Transition"
status = "generate"
	[[object.function]]
	name = "return_error"
	manual = true

[[object]]
name = "Wp.SpaPod"
status = "generate"
	[[object.function]]
	name = "get_spa_type"
	manual = true

[[object]]
name = "Wp.SpaPodParser"
status = "generate"
	[[object.function]]
	name = "new_object"
	ignore = true

[[object]]
name = "Wp.Properties"
status = "generate"
	[[object.derive]]
	name = "PartialEq, Eq, PartialOrd, Ord, Hash" # defaults excluding Debug

[[object]]
name = "Wp.PropertiesItem"
status = "generate"
# TODO: work around gir bug, 0.14 omitted the entire struct properly
cfg_condition = 'feature = "v0_4_2"'

[[object]]
name = "Wp.Iterator"
status = "generate"
	[[object.function]]
	name = "new"
	ignore = true

[[object]]
name = "Wp.ObjectFeatures"
status = "manual"
conversion_type = "scalar"

[[object]]
name = "Wp.PipewireObject"
status = "generate"
	[[object.function]]
	name = "get_property"
	manual = true

# enums

[[object]]
name = "Wp.ConstraintVerb"
status = "generate"
generate_display_trait = true

[[object]]
name = "Wp.ConstraintType"
status = "generate"
generate_display_trait = true

[[object]]
name = "Wp.Direction"
status = "generate"
generate_display_trait = true

[[object]]
name = "Wp.LibraryErrorEnum"
status = "generate"
generate_display_trait = true

[[object]]
name = "Wp.NodeState"
status = "generate"
generate_display_trait = true

[[object]]
name = "Wp.DBusState"
status = "generate"
generate_display_trait = true

[[object]]
name = "Wp.LinkState"
status = "generate"
generate_display_trait = true

[[object]]
name = "Wp.SiAdapterPortsState"
status = "generate"
generate_display_trait = true

[[object]]
name = "Wp.TransitionStep"
status = "generate"
generate_display_trait = true

# flags

[[object]]
name = "Wp.LinkFeatures"
status = "generate"
version = "" # fails to parse, so removes cfg
	[[object.member]]
	# instead, apply the version cfg to all defined bits instead
	pattern = ".*"
	version = "0.4.11"
