[package]
name = "wireplumber-sys"
version = "0.1.0"
edition = "2018"
build = "../generate/build.rs"

[package.metadata.system-deps.wireplumber_0_4]
name = "wireplumber-0.4"
version = "0.4"

[package.metadata.system-deps.wireplumber_0_4.v0_4_2]
version = "0.4.2"

[package.metadata.system-deps.wireplumber_0_4.v0_4_3]
version = "0.4.3"

[package.metadata.docs.rs]
features = ["dox"]

[lib]
name = "wp_sys"

[dependencies]
libc = "0.2"
glib = { version = "0.14", package = "glib-sys" }
gobject = { version = "0.14", package = "gobject-sys" }
gio = { version = "0.14", package = "gio-sys" }
pipewire = { version = "0.4", package = "pipewire-sys" }
libspa = { version = "0.4", package = "libspa-sys" }

[build-dependencies]
system-deps = "6"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
v0_4_2 = []
v0_4_3 = ["v0_4_2"]
dox = []
