[package]
name = "wp-examples"
version = "0.0.0"
authors = ["arcnmx"]
edition = "2018"
build = "build.rs"

[[bin]]
name = "wpexec"
path = "src/bin/exec.rs"

[[example]]
name = "static-link-module"
crate-type = ["cdylib"]
path = "src/static-link.rs"

[dependencies]
futures = "0.3"
wireplumber = { version = "0.1", features = ["enable-futures", "enable-libspa", "enable-serde", "v0_4_3"], path = "../" }
pipewire-sys = "0.5"
glib = { version = "0.16", git = "https://github.com/gtk-rs/gtk-rs-core" }
ctrlc = { version = "3.0", features = ["termination"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "3.0", features = ["derive"] }
anyhow = "1.0"
